### ISSUE TITLE
MatchBlades_AAchen_2D 

### ISSUE THREAD

**Issue by miamosin** [NAnand-TUD/parablade#7]
Hello  Nitish,
I would like to parameterize the 2D and 3D model of a Blade whose geometry is known (CAD). This means that I already have the characteristics of the Blade geometry (stagger,theta_in,theta_ou,wedge_in ...) . My question is how to use MatchBlades. Because when I replace the coordinates of the geometry there is no way for me to be able to compile in order to get the 2d or then 3D model of the blade. 
How can I use MatchBlade ? because with the example that you gave us I can't get a 2D or 3D model. 
Do you have a concrete examplet hat could help me? 
Thank you and have a good weekend 
Best Regards. 
Clement Singoue

**Comment by NAnand-TUD** [comment]
Dear Clement, Thanks for reaching out. Please have a look at the folder /testcases/MatchBlades/ here you will find all the working examples that we have. 

Regarding matching the characteristics. While using match blade you can interactively work on the ParaBlade config file and update it so as to match the characteristics of the blade you wish to match. The characteristics will not match exactly with the ParaBlade and that of your blades, this is because the definitions of the two blades can be very different. Hence, the best is to get the best parameters to accurately represent your blade.

If you have more questions please do not hesitate to continue this thread.

Thanks,
Nitish

**Comment by miamosin** [comment]
Dear Dr. Nitish,
Thank you for our answer which allowed me to understand how Parablade Works. But I am now facing a difficulty to Know how to generate the txt file that has the coordinates (xyz) of the Blade after defined the coordinates and the gemetrical properties of the Blade in "Parablade configuration file"? 
Tank you an nice start of the Week :) .
Best Regards. 
Clement

**Comment by miamosin** [comment]
Hello Nitish,
I have crated the 2D model of my Blade (Axial Compressorblade)   but I have a Problem to defining the coordinates of the Inlet an Outlet for a Flow Simulation in Ansys CFX (Boundary Conditions). I would like to know what are variables in MachtBlade that allow me to define the coordinates of the Inlet and the Outlet. 
Best Regards.
Clement Singoue

**Comment by z-g-h** [comment]
hello Nitish,
Thanks for opening your code, I want to know that the index has any special mean in the file /testcases/MatchBlades/Aachen_3D/moveSurface.txt.
Thanks.
